name: Deploy to My Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: production
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build Application
        run: ./gradlew build --info

      - name: Debug - List files
        run: |
          echo "Current directory: $(pwd)"
          ls -l ./build/libs/
          find . -name "*.jar"

      - name: Copy file via SSH key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./build/libs/pro-0.0.1-SNAPSHOT.jar"
          target: "/home/yusm1231/kelog/backend/pro-0.0.1-SNAPSHOT.jar"
          strip_components: 3

      - name: Execute deploy script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            /home/yusm1231/kelog/backend/deploy.sh
