name: Deploy to My Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SPRING_PROFILES_ACTIVE: production
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      # 소스코드를 체크아웃
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      # JDK 21 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
          
      # gradlew에 실행 권한 부여
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      # 애플리케이션 빌드
      - name: Build Application
        run: ./gradlew build

      # 빌드된 파일을 주요 서버로 전송
      - name: Copy file via SSH key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./build/libs/pro-0.0.1-SNAPSHOT.jar"
          target: "/home/yusm1231/kelog/backend/pro-0.0.1-SNAPSHOT.jar"
          
      # 서버에 배포 스크립트 실행
      - name: Execute deploy script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            /home/yusm1231/kelog/backend/deploy.sh
